name: formatMaps

on:
  pull_request:

permissions:
  contents: write

jobs:
  formatMaps:
    name: FormatMaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: SetupShinkrodb
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/varoOP/shinkrodb/releases/download/v0.1.2/shinkrodb_v0.1.2_linux_amd64.tar.gz"
          name: "shinkrodb"
          version: "0.1.2"

      - name: FormatMaps
        run: |
          shinkrodb format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format maps
